name: Build

on:
    push:
        tags:
            - v*.*.*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
          include:
#              - os: ubuntu-latest
#                arch: [arm64, amd64]
              - os: macos-latest
                arch: [arm64, amd64]
              - os: windows-latest
                arch: [arm64, amd64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Prepare (macOS)
        if: runner.os == 'macOS'
        run: |
            brew install python-setuptools

      - name: Cert Prepare (macOS)
        if: runner.os == 'macOS'
        env:
            MACOS_CERTIFICATE: ${{ secrets.CORP_MACOS_CERTIFICATE }}
            MACOS_CERTIFICATE_PASSWORD: ${{ secrets.CORP_MACOS_CERTIFICATE_PASSWORD }}
        run: |
            echo "find-identity"
            security find-identity -p codesigning
            echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
            security import certificate.p12 -P "$MACOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
            echo "find-identity"
            security find-identity -p codesigning

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Release Assets
        uses: softprops/action-gh-release@v2
        with:
            draft: false
            prerelease: false
            fail_on_unmatched_files: false
            files: |
                dist-release/*.exe
                dist-release/*.dmg
                dist-release/*.AppImage
                dist-release/*.deb
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

